In [123]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import holoviews as hv
import hvplot.pandas
import panel as pn
from tqdm import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed
import multiprocessing as mp

from scipy import stats
from pathlib import Path
from pprint import pprint
from holoviews import opts
from bokeh.io import output_notebook


output_notebook()
hv.extension('bokeh')

font_dict = {'title': 16, 'labels': 14, 'ticks': 12, 'legend': 12}
hv.opts.defaults(
    hv.opts.Curve(width=600, height=400, tools=['hover'], fontsize=font_dict),
    hv.opts.Scatter(width=600, height=400, size=8, tools=['hover'], fontsize=font_dict),
    hv.opts.Histogram(width=600, height=400, fontsize=font_dict),
    hv.opts.Bars(width=600, height=400, fontsize=font_dict),
)

In [142]:
monkey = 'fiona' # 'yasmin'  or 'fiona' 
base_path = Path.cwd().parent / 'data' / 'csst_trials_pkls'
filepath = base_path / f'all_{monkey}_CSST_trials_df.pkl'
df = pd.read_pickle(filepath)

# print(df.info())
# df.iloc[:2]
print(df.columns)
df

Index(['blinks', 'dir', 'direction', 'filename', 'first_relevant_saccade',
       'flags', 'go_cue', 'hPos', 'hVel', 'neural_data', 'reaction_time',
       'saccades', 'screen_rotation', 'segs_durations', 'segs_times', 'set',
       'speed', 'ssd_len', 'ssd_number', 'stop_cue', 'trial_failed',
       'trial_length', 'trial_name', 'trial_number', 'trial_session', 'type',
       'vPos', 'vVel'],
      dtype='object')

,blinks,dir,direction,filename,first_relevant_saccade,flags,go_cue,hPos,hVel,neural_data,...,ssd_number,stop_cue,trial_failed,trial_length,trial_name,trial_number,trial_session,type,vPos,vVel
0,None,180,L,fi210824a.0614,"[1382, 1457]",8206,1054,"[11.275, 11.275, 11.275, 11.275, 11.275, 11.27...","[0.0, 0.0, 0.4594490287247533, 1.3783470861742...","{0: [884.4], 1: [154.42, 329.18, 1478.9], 3: [...",...,2.0,1186.0,False,2205,CONT_L_SSD2,0614,fi210824a,CONT,"[-0.05, -0.05, -0.05, -0.05, -0.05, -0.05, 0.0...","[-3.1242533953283225, -3.1242533953283225, -4...."
1,None,180,L,fi210824a.0520,"[1100, 1172]",8206,914,"[-11.15, -11.15, -11.15, -11.15, -11.15, -11.1...","[-2.7566941723485194, -2.7566941723485194, -3....","{1: [48.52, 264.55, 585.97, 1032.3], 2: [385.2...",...,NaN,NaN,False,2065,GO_L,0520,fi210824a,GO,"[-1.15, -1.15, -1.15, -1.15, -1.15, -1.175, -1...","[-0.8270082517045559, -0.8270082517045559, 0.1..."
2,None,180,L,fi210824a.1193,"[1099, 1179]",8206,938,"[2.25, 2.25, 2.3, 2.3, 2.3, 2.25, 2.225, 2.225...","[-188.19032216565896, -188.19032216565896, -18...","{1: [574.7, 853.02, 1403.57], 3: [8.35, 301.92...",...,3.0,1118.0,False,2089,CONT_L_SSD3,1193,fi210824a,CONT,"[-27.45, -27.45, -27.45, -27.45, -27.45, -27.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 9.280870380240016, 4..."
3,None,180,L,fi210824a.1013,"[1213, 1289]",13326,1081,"[8.425, 8.425, 8.375, 8.375, 8.375, 8.4, 8.4, ...","[1.286457280429309, 1.286457280429309, -0.9188...","{2: [1954.73], 5: [434.05, 484.13, 547.7, 851....",...,3.0,1261.0,True,1961,STOP_L_SSD3,1013,fi210824a,STOP,"[0.275, 0.275, 0.275, 0.275, 0.275, 0.275, 0.2...","[0.9188980574495066, 0.9188980574495066, 0.0, ..."
4,None,0,R,fi210824a.1257,NaN,8194,1024,"[-11.475, -11.475, -11.475, -11.475, -11.475, ...","[3.767482035542977, 3.767482035542977, 3.85937...","{0: [923.35], 1: [1125], 5: [1026.4, 1359.92, ...",...,2.0,1156.0,True,1476,CONT_R_SSD2,1257,fi210824a,CONT,"[-1.825, -1.825, -1.8, -1.8, -1.825, -1.825, -...","[0.27566941723485194, 0.27566941723485194, 1.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110353,None,0,R,fi211020a.0230,"[1213, 1285]",8206,943,"[-9.925, -9.925, -9.925, -9.925, -9.95, -9.95,...","[-0.09188980574495066, -0.09188980574495066, -...","{0: [1937.51], 1: [24.51, 42.58, 111.86, 173.7...",...,NaN,NaN,False,2094,GO_R,0230,fi211020a,GO,"[-1.35, -1.35, -1.45, -1.45, -1.35, -1.35, -1....","[-1.8377961148990132, -1.8377961148990132, -3...."
110354,None,0,R,fi211020a.0832,"[1397, 1470]",8206,1070,"[-11.925, -11.925, -11.85, -11.85, -11.875, -1...","[-4.686380092992484, -4.686380092992484, 0.0, ...","{0: [1027.96], 1: [19.86, 91.81, 177.64, 261.5...",...,NaN,NaN,False,2221,GO_R,0832,fi211020a,GO,"[-0.7, -0.7, -0.625, -0.625, -0.675, -0.675, -...","[-3.3080330068182238, -3.3080330068182238, 0.2..."
110355,None,180,L,fi211020a.1304,"[1210, 1287]",8206,1051,"[-11.95, -11.95, -11.95, -11.95, -11.95, -11.9...","[2.389134949368717, 0.5513388344697039, 0.5513...","{0: [16.69, 27.66, 37.08, 89.74, 120.56, 218.7...",...,NaN,NaN,False,2202,GO_L,1304,fi211020a,GO,"[0.725, 0.75, 0.75, 0.775, 0.75, 0.75, 0.725, ...","[-1.6540165034091119, -1.1026776689394078, -1...."
110356,None,180,L,fi211020a.0719,"[1123, 1197]",8194,1001,"[0.0, 0.0, -0.1, -0.175, -0.175, -0.175, -0.37...","[-51.090731994192566, -51.090731994192566, -50...","{0: [521.64, 535.58, 677.96, 741.66, 963.88, 9...",...,NaN,NaN,True,2057,GO_L,0719,fi211020a,GO,"[-4.425, -4.425, -3.35, -3.0, -2.65, -2.65, -1...","[188.098432359914, 188.098432359914, 188.09843..."
110357,None,0,R,fi211020a.0901,"[1133, 1183]",8206,1085,"[11.375, 11.375, 11.375, 11.375, 11.375, 11.37...","[1.1026776689394078, 1.1026776689394078, 1.286...","{0: [41.91, 623.49, 1034.24, 1483.94, 1847.24]...",...,NaN,NaN,False,2236,GO_R,0901,fi211020a,GO,"[-0.425, -0.425, -0.4, -0.425, -0.425, -0.425,...","[-1.3783470861742597, -1.3783470861742597, 1.0..."

In [140]:
def get_cells_count_in_neural_data(trial):
    neural_data = trial['neural_data']
    if neural_data is None:
        return 0
    return len(neural_data.keys())  # number of cells

trial = df.iloc[0]
num_cells = get_cells_count_in_neural_data(trial)
print(f'Number of cells in first trial: {num_cells}')
trial['neural_data']

df.apply(get_cells_count_in_neural_data, axis=1)

Number of cells in first trial: 9

0          9
1          9
2          9
3         10
4         10
          ..
110353    72
110354    73
110355    54
110356    73
110357    71
Length: 110358, dtype: int64

In [126]:
df['filename'].apply(lambda x: x.split('.')[0][-1]).unique()

array(['a'], dtype=object)

In [127]:
# Drop unnecessary columns
cols_to_drop = [
    'vPos', 'hPos', 'vVel', 'hVel', 'speed',
    'set', 'direction'
]
df.drop(columns=cols_to_drop, inplace=True)
print(f"DataFrame shape after dropping columns: {df.shape}")
# df.head()

DataFrame shape after dropping columns: (110358, 21)

In [128]:
# reorder columns
new_order = [
    'filename', 'trial_name', 'reaction_time', 
    'go_cue', 'stop_cue', 'trial_failed', 
    'first_relevant_saccade', 'segs_durations', 'segs_times',
    'trial_length', 'ssd_len', 'ssd_number',
    'screen_rotation', 'neural_data', 'saccades', 
    'blinks', 'dir', 'flags',
    'type', 'trial_session', 'trial_number',
]

df = df[new_order]
# df.head()

In [129]:
df['filename']

0         fi210824a.0614
1         fi210824a.0520
2         fi210824a.1193
3         fi210824a.1013
4         fi210824a.1257
               ...
110353    fi211020a.0230
110354    fi211020a.0832
110355    fi211020a.1304
110356    fi211020a.0719
110357    fi211020a.0901
Name: filename, Length: 110358, dtype: object

In [130]:
# load monkey's cell db from xlsx file
cell_db_path = Path.cwd().parent / 'data' / f'database_sst'
cell_db = pd.read_excel(cell_db_path / f'SST_{monkey}_cells_db.xlsx')
print(cell_db.info())
cell_db.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5309 entries, 0 to 5308
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   cell_ID              5309 non-null   int64
 1   session              5309 non-null   object
 2   cell_type            5309 non-null   object
 3   electrode            5309 non-null   int64
 4   template             5309 non-null   int64
 5   maestro_ID           5309 non-null   int64
 6   phy_id               0 non-null      float64
 7   phy_channel          0 non-null      float64
 8   file_begin           5309 non-null   int64
 9   file_end             5309 non-null   int64
 10  fb_after_stablility  5309 non-null   object
 11  fe_after_stability   5309 non-null   object
 12  plexon_session       5309 non-null   object
 13  grade                5309 non-null   int64
 14  X                    5309 non-null   int64
 15  Y                    5309 non-null   int64
 16  depth_mm             1276 non-null   float64
 17  is_continuous        5309 non-null   int64
 18  comments             144 non-null    object
 19  plex_sorted_file     5309 non-null   object
 20  tmp                  5265 non-null   float64
 21  sorted               5309 non-null   int64
 22  problem              11 non-null     object
 23  synced_stability     5309 non-null   int64
dtypes: float64(4), int64(12), object(8)
memory usage: 995.6+ KB
None

,cell_ID,session,cell_type,electrode,template,maestro_ID,phy_id,phy_channel,file_begin,file_end,...,X,Y,depth_mm,is_continuous,comments,plex_sorted_file,tmp,sorted,problem,synced_stability
0,9001,fi210628,ctx,1,1,1,NaN,NaN,1,225,...,0,0,4420.0,2,depth micro m is from cortex surface,fi210628a-01.pl2,NaN,1,broken cell two peaks,1
1,9002,fi210629,msn,1,1,1,NaN,NaN,84,163,...,0,-1,10200.0,2,NaN,fi210629a-01.pl2,NaN,1,NaN,1
2,9003,fi210701,msn,1,1,1,NaN,NaN,16,348,...,0,-1,7030.0,2,2 cells multi unit,fi210701a-02.pl2,NaN,1,NaN,1
3,9004,fi210701,tan,1,1,1,NaN,NaN,350,510,...,0,-1,7110.0,2,NaN,fi210701b-02.pl2,NaN,1,NaN,1
4,9005,fi210701,msn,1,2,2,NaN,NaN,16,348,...,0,-1,7030.0,2,NaN,fi210701a-02.pl2,NaN,1,NaN,1

In [131]:
cell_db.columns

Index(['cell_ID', 'session', 'cell_type', 'electrode', 'template',
       'maestro_ID', 'phy_id', 'phy_channel', 'file_begin', 'file_end',
       'fb_after_stablility', 'fe_after_stability', 'plexon_session', 'grade',
       'X', 'Y', 'depth_mm', 'is_continuous', 'comments', 'plex_sorted_file',
       'tmp', 'sorted', 'problem', 'synced_stability'],
      dtype='object')

In [153]:
msn_cells = cell_db[
    cell_db['cell_type'].isin(['msn', 'pu msn']) &
    (cell_db['grade'] <= 100) 
].copy().reset_index(drop=True)
print(f'Number of MSN cells: {len(msn_cells)}')

Number of MSN cells: 4206

In [154]:
tmp = cell_db[
    ~cell_db['fe_after_stability'].apply(
        lambda x: isinstance(x, int)
    )
][['fe_after_stability', 'fb_after_stablility']] 

tmp['fe_after_stability'] = tmp['fe_after_stability'].apply(
    lambda x: np.fromstring(x.strip('[]'), sep=' ')
)

tmp['fb_after_stablility'] = tmp['fb_after_stablility'].apply(
    lambda x: np.fromstring(x.strip('[]'), sep=' ')
)

tmp['comp'] = tmp.apply(
    lambda row: len(row['fe_after_stability']) == len(row['fb_after_stablility']), axis=1
) 

#- cell_db['fb_after_stablility'].astype(int)

In [155]:
def process_cells_stability(row):
    fe = row['fe_after_stability']
    fb = row['fb_after_stablility']

    if isinstance(fe, np.ndarray) and isinstance(fb, np.ndarray):
        return fe, fb
    
    if isinstance(fe, int) and isinstance(fb, int):
        return fe, fb
    
    fe_array = np.fromstring(fe.strip('[]'), sep=' ')
    fb_array = np.fromstring(fb.strip('[]'), sep=' ')
    
    return fe_array, fb_array

msn_cells[['fe_after_stability', 'fb_after_stablility']] = msn_cells.apply(
    process_cells_stability, axis=1, result_type='expand'
)

In [156]:
msn_cells[
    ~msn_cells.apply(
    lambda row: isinstance(row['fe_after_stability'], int), axis=1
)].apply(
    lambda row: type(row['fe_after_stability']), axis=1
).value_counts()

<class 'numpy.ndarray'>    91
Name: count, dtype: int64

In [157]:
(msn_cells['fe_after_stability'] - msn_cells['fb_after_stablility']).apply(
    lambda x: x if not isinstance(x, np.ndarray) else x.sum()
).sum().astype(int)

np.int64(2806628)

In [216]:
minimal_df = msn_cells[
    [
        'session', 'cell_ID', 
        'fe_after_stability', 'fb_after_stablility',
        'maestro_ID', 'plexon_session'    
    ]
]

def get_trials_range(row):
    fe = row['fe_after_stability']
    fb = row['fb_after_stablility']
    
    session = row['session']
    # cell_ID = row['cell_ID']
    # maestro_ID = row['maestro_ID']
    plexon_session = 'a' #row['plexon_session']

    row_trials = []
    if isinstance(fe, int) and isinstance(fb, int):
        for trial_num in range(fb, fe + 1):
            row_trials.append(f"{session}{plexon_session}.{trial_num:04d}")
    elif isinstance(fe, np.ndarray) and isinstance(fb, np.ndarray):
        for start, end in zip(fe, fb):
            for trial_num in range(int(start), int(end) + 1):
                row_trials.append(f"{session}{plexon_session}.{trial_num:04d}")
    else:
        raise ValueError(f"Unexpected types for fe and fb: {type(fe)}, {type(fb)}")
    return row_trials

minimal_df['trials_list'] = minimal_df.apply(get_trials_range, axis=1)


minimal_df['trials_list'].iloc[0]

/tmp/ipykernel_72252/2658607796.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  minimal_df['trials_list'] = minimal_df.apply(get_trials_range, axis=1)

['fi210629a.0084',
 'fi210629a.0085',
 'fi210629a.0086',
 'fi210629a.0087',
 'fi210629a.0088',
 'fi210629a.0089',
 'fi210629a.0090',
 'fi210629a.0091',
 'fi210629a.0092',
 'fi210629a.0093',
 'fi210629a.0094',
 'fi210629a.0095',
 'fi210629a.0096',
 'fi210629a.0097',
 'fi210629a.0098',
 'fi210629a.0099',
 'fi210629a.0100',
 'fi210629a.0101',
 'fi210629a.0102',
 'fi210629a.0103',
 'fi210629a.0104',
 'fi210629a.0105',
 'fi210629a.0106',
 'fi210629a.0107',
 'fi210629a.0108',
 'fi210629a.0109',
 'fi210629a.0110',
 'fi210629a.0111',
 'fi210629a.0112',
 'fi210629a.0113',
 'fi210629a.0114',
 'fi210629a.0115',
 'fi210629a.0116',
 'fi210629a.0117',
 'fi210629a.0118',
 'fi210629a.0119',
 'fi210629a.0120',
 'fi210629a.0121',
 'fi210629a.0122',
 'fi210629a.0123',
 'fi210629a.0124',
 'fi210629a.0125',
 'fi210629a.0126',
 'fi210629a.0127',
 'fi210629a.0128',
 'fi210629a.0129',
 'fi210629a.0130',
 'fi210629a.0131',
 'fi210629a.0132',
 'fi210629a.0133',
 'fi210629a.0134',
 'fi210629a.0135',
 'fi210629a.0136',
 'fi210629a.0137',
 'fi210629a.0138',
 'fi210629a.0139',
 'fi210629a.0140',
 'fi210629a.0141',
 'fi210629a.0142',
 'fi210629a.0143',
 'fi210629a.0144',
 'fi210629a.0145',
 'fi210629a.0146',
 'fi210629a.0147',
 'fi210629a.0148',
 'fi210629a.0149',
 'fi210629a.0150',
 'fi210629a.0151',
 'fi210629a.0152',
 'fi210629a.0153',
 'fi210629a.0154',
 'fi210629a.0155',
 'fi210629a.0156',
 'fi210629a.0157',
 'fi210629a.0158',
 'fi210629a.0159',
 'fi210629a.0160',
 'fi210629a.0161',
 'fi210629a.0162',
 'fi210629a.0163']

In [217]:
trials_set = set()

for i, row in minimal_df.iterrows():
    trials = row['trials_list']
    trials_set.update(trials)

len(trials_set)
trials_set

{'fi210726a.0709',
 'fi211108a.0675',
 'fi211018a.1196',
 'fi211104a.2339',
 'fi211123a.2072',
 'fi210902a.1033',
 'fi210729a.0297',
 'fi210927a.0316',
 'fi210719a.1463',
 'fi210819a.1170',
 'fi211018a.0910',
 'fi210818a.0428',
 'fi210823a.0810',
 'fi211026a.0448',
 'fi211117a.1780',
 'fi210714a.1044',
 'fi211118a.2056',
 'fi211012a.1606',
 'fi210819a.0202',
 'fi210726a.0366',
 'fi211115a.1343',
 'fi210816a.0356',
 'fi211014a.0592',
 'fi211026a.0984',
 'fi210908a.0769',
 'fi210831a.0568',
 'fi210908a.0002',
 'fi210815a.0523',
 'fi210812a.1628',
 'fi211020a.0257',
 'fi210729a.0683',
 'fi210907a.0237',
 'fi210908a.0384',
 'fi211109a.0582',
 'fi211104a.1101',
 'fi211019a.0546',
 'fi211118a.2043',
 'fi210811a.1482',
 'fi211017a.0184',
 'fi211018a.1222',
 'fi211118a.2045',
 'fi210729a.0532',
 'fi211104a.1059',
 'fi210819a.1087',
 'fi211026a.0107',
 'fi210811a.0113',
 'fi210823a.1178',
 'fi210815a.0830',
 'fi211125a.1289',
 'fi210817a.0904',
 'fi210819a.0963',
 'fi211109a.0246',
 'fi211018a.0643',
 'fi211017a.2193',
 'fi210728a.0193',
 'fi210810a.1241',
 'fi210727a.0844',
 'fi211102a.1892',
 'fi211012a.1556',
 'fi211125a.1180',
 'fi211012a.0250',
 'fi211125a.0806',
 'fi210823a.1119',
 'fi211104a.0778',
 'fi211125a.1471',
 'fi211102a.1904',
 'fi210810a.0350',
 'fi210817a.0123',
 'fi211124a.0064',
 'fi211025a.1188',
 'fi211111a.1120',
 'fi210719a.1112',
 'fi211123a.0846',
 'fi210720a.1303',
 'fi210831a.0688',
 'fi210823a.1191',
 'fi211108a.0605',
 'fi211124a.0264',
 'fi210801a.0740',
 'fi211108a.0163',
 'fi211103a.0493',
 'fi211118a.1898',
 'fi210712a.0558',
 'fi211117a.1551',
 'fi210909a.1226',
 'fi211125a.1608',
 'fi211123a.1695',
 'fi210815a.0395',
 'fi211010a.0043',
 'fi211122a.0479',
 'fi211124a.0100',
 'fi210719a.1090',
 'fi210729a.0118',
 'fi210824a.0195',
 'fi211017a.1000',
 'fi210927a.0131',
 'fi210909a.0745',
 'fi210817a.1037',
 'fi211012a.0390',
 'fi211117a.2032',
 'fi211115a.0942',
 'fi210725a.0119',
 'fi210720a.1396',
 'fi211103a.2027',
 'fi211026a.0999',
 'fi210816a.0579',
 'fi211019a.0235',
 'fi211110a.1544',
 'fi210812a.0842',
 'fi211012a.1325',
 'fi211110a.1818',
 'fi210725a.0645',
 'fi211012a.1735',
 'fi210729a.1035',
 'fi211103a.1146',
 'fi210811a.1860',
 'fi210811a.1514',
 'fi210901a.0982',
 'fi211108a.1935',
 'fi210722a.0633',
 'fi211014a.0442',
 'fi210822a.0907',
 'fi210719a.0961',
 'fi211025a.1552',
 'fi211115a.1946',
 'fi210818a.0553',
 'fi210727a.0360',
 'fi211110a.0285',
 'fi210718a.0228',
 'fi210811a.0618',
 'fi210822a.0560',
 'fi210811a.0677',
 'fi211025a.1269',
 'fi211017a.1808',
 'fi211111a.1528',
 'fi211012a.0697',
 'fi210720a.0354',
 'fi210728a.0161',
 'fi210901a.0106',
 'fi210809a.1119',
 'fi211026a.0562',
 'fi210714a.0466',
 'fi210830a.0510',
 'fi211108a.1864',
 'fi211025a.2020',
 'fi210901a.0777',
 'fi211026a.1501',
 'fi211012a.0491',
 'fi211110a.1221',
 'fi210715a.0211',
 'fi211017a.0989',
 'fi210727a.1010',
 'fi211117a.2252',
 'fi211019a.0862',
 'fi211109a.0048',
 'fi211117a.1449',
 'fi210908a.0948',
 'fi210718a.0120',
 'fi210901a.0125',
 'fi211122a.0734',
 'fi210810a.1343',
 'fi210816a.0977',
 'fi210726a.0142',
 'fi210831a.0731',
 'fi210727a.0546',
 'fi211111a.1738',
 'fi210725a.0834',
 'fi211123a.0703',
 'fi211104a.1223',
 'fi211019a.1510',
 'fi211012a.1136',
 'fi210831a.0065',
 'fi210725a.0870',
 'fi210819a.0721',
 'fi210908a.0072',
 'fi210817a.1105',
 'fi211115a.1415',
 'fi211021a.0443',
 'fi210823a.0809',
 'fi210902a.0426',
 'fi210725a.0192',
 'fi211125a.1677',
 'fi211104a.1316',
 'fi211123a.1269',
 'fi210830a.0267',
 'fi210909a.0765',
 'fi211012a.0395',
 'fi211014a.1325',
 'fi210713a.0608',
 'fi210902a.0080',
 'fi210817a.0783',
 'fi211026a.0223',
 'fi211118a.1257',
 'fi211017a.0192',
 'fi211012a.1619',
 'fi211122a.1794',
 'fi211108a.0838',
 'fi211108a.1934',
 'fi211115a.1315',
 'fi210809a.0632',
 'fi210901a.0940',
 'fi211012a.1787',
 'fi211110a.1441',
 'fi210725a.0128',
 'fi211102a.1611',
 'fi211125a.1609',
 'fi211025a.0643',
 'fi210823a.0510',
 'fi210823a.0688',
 'fi211017a.1815',
 'fi211123a.2208',
 'fi211118a.0449',
 'fi210712a.0245',
 'fi211110a.0311',
 'fi211102a.0106',
 'fi210908a.0424',
 'fi211017a.1849',
 'fi211021a.0134',
 'fi211102a.1797',
 'fi210714a.0476',
 'fi210818a.0543',
 'fi211102a.1069',
 'fi211123a.1526',
 'fi211125a.0248',
 'fi211025a.0369',
 'fi211110a.0915',
 'fi211122a.0688',
 'fi210727a.0901',
 'fi211017a.1727',
 'fi211104a.2000',
 'fi210705a.0324',
 'fi211115a.1260',
 'fi211103a.2051',
 'fi210927a.0621',
 'fi211018a.0337',
 'fi211020a.0128',
 'fi210811a.1534',
 'fi211110a.1660',
 'fi210727a.0560',
 'fi210809a.0248',
 'fi210721a.0257',
 'fi210816a.0967',
 'fi211122a.0615',
 'fi210901a.1054',
 'fi211123a.0126',
 'fi210722a.1116',
 'fi210810a.1200',
 'fi210705a.0082',
 'fi211018a.1386',
 'fi211110a.0183',
 'fi210822a.0036',
 'fi210818a.0554',
 'fi211104a.0392',
 'fi211117a.1496',
 'fi211017a.0033',
 'fi210810a.1348',
 'fi211118a.1749',
 'fi211108a.2437',
 'fi211019a.0467',
 'fi211125a.1307',
 'fi210830a.0098',
 'fi211019a.0618',
 'fi211109a.1374',
 'fi210712a.0603',
 'fi211017a.2334',
 'fi211104a.0634',
 'fi210809a.0573',
 'fi211103a.1801',
 'fi210831a.1162',
 'fi210909a.0027',
 'fi210715a.0090',
 'fi211123a.0381',
 'fi210823a.0351',
 'fi211104a.0817',
 'fi211103a.1744',
 'fi210817a.0203',
 'fi211025a.0860',
 'fi211109a.0818',
 'fi210811a.0288',
 'fi211021a.0531',
 'fi211103a.2219',
 'fi210726a.0241',
 'fi211025a.0068',
 'fi211122a.0170',
 'fi210909a.0201',
 'fi210811a.1912',
 'fi211115a.1941',
 'fi210831a.0597',
 'fi210901a.1577',
 'fi211017a.2566',
 'fi211017a.1932',
 'fi211117a.0833',
 'fi210722a.0595',
 'fi211109a.0323',
 'fi211122a.0101',
 'fi211021a.0646',
 'fi210817a.0380',
 'fi210815a.0327',
 'fi210908a.0213',
 'fi211103a.1824',
 'fi211118a.0908',
 'fi210712a.0495',
 'fi210902a.0133',
 'fi210817a.0244',
 'fi210902a.0984',
 'fi211123a.2299',
 'fi210719a.0364',
 'fi210728a.0256',
 'fi210830a.0380',
 'fi210809a.0388',
 'fi210909a.1444',
 'fi211026a.1387',
 'fi210819a.0686',
 'fi210823a.0430',
 'fi211019a.0017',
 'fi211111a.1837',
 'fi211110a.1391',
 'fi211012a.1830',
 'fi210815a.0374',
 'fi211018a.1238',
 'fi211019a.1434',
 'fi210816a.0876',
 'fi210728a.0145',
 'fi210714a.0178',
 'fi210810a.0748',
 'fi211026a.0558',
 'fi210729a.0798',
 'fi210726a.0229',
 'fi210811a.0620',
 'fi210818a.1181',
 'fi211018a.1737',
 'fi210817a.1076',
 'fi211019a.1382',
 'fi210727a.0028',
 'fi211117a.0080',
 'fi210816a.0204',
 'fi211026a.0671',
 'fi211123a.2217',
 'fi210811a.0255',
 'fi210811a.0304',
 'fi211025a.0682',
 'fi210714a.0548',
 'fi211103a.0360',
 'fi211117a.1481',
 'fi211103a.0916',
 'fi211108a.0490',
 'fi210701a.0341',
 'fi210817a.1224',
 'fi210817a.0365',
 'fi211012a.1197',
 'fi211021a.1196',
 'fi211018a.0991',
 'fi210902a.0845',
 'fi211102a.1698',
 'fi210909a.0723',
 'fi210823a.0099',
 'fi211123a.2238',
 'fi210811a.0856',
 'fi210712a.0292',
 'fi210725a.0097',
 'fi211012a.1750',
 'fi210726a.0204',
 'fi211018a.0797',
 'fi210823a.0283',
 'fi211125a.1780',
 'fi210810a.0742',
 'fi210901a.0864',
 'fi211108a.1448',
 'fi210811a.1247',
 'fi210909a.1204',
 'fi210817a.0898',
 'fi210831a.0615',
 'fi211017a.2234',
 'fi210810a.0141',
 'fi211108a.0506',
 'fi210722a.0187',
 'fi210718a.0227',
 'fi211012a.0820',
 'fi211124a.1103',
 'fi210909a.0818',
 'fi210719a.1342',
 'fi211123a.1148',
 'fi210715a.1257',
 'fi210927a.0362',
 'fi211124a.0495',
 'fi210909a.0227',
 'fi211025a.1421',
 'fi210801a.0193',
 'fi210714a.0141',
 'fi210718a.0453',
 'fi211014a.0973',
 'fi211118a.1243',
 'fi211117a.0001',
 'fi210729a.1148',
 'fi210726a.0344',
 'fi210719a.0356',
 'fi211111a.0676',
 'fi211019a.0963',
 'fi211010a.0499',
 'fi210728a.0377',
 'fi210824a.0550',
 'fi211118a.1957',
 'fi210831a.0749',
 'fi210701a.0069',
 'fi210819a.0719',
 'fi211125a.1551',
 'fi211025a.1748',
 'fi210713a.0143',
 'fi211123a.0581',
 'fi210822a.0009',
 'fi210729a.1008',
 'fi210801a.0472',
 'fi211104a.1965',
 'fi211117a.1352',
 'fi210712a.0768',
 'fi211125a.0750',
 'fi211019a.1859',
 'fi210729a.0077',
 'fi210901a.0205',
 'fi211124a.0073',
 'fi210707a.0575',
 'fi210714a.0323',
 'fi211018a.0739',
 'fi211025a.1493',
 'fi211117a.2169',
 'fi211017a.2219',
 'fi211018a.0903',
 'fi211122a.1682',
 'fi210817a.1217',
 'fi210901a.0569',
 'fi211019a.1671',
 'fi211014a.0948',
 'fi211019a.1792',
 'fi210801a.0796',
 'fi211123a.0601',
 'fi210718a.0071',
 'fi211123a.2132',
 'fi210715a.0202',
 'fi210719a.0633',
 'fi210816a.1224',
 'fi211118a.0603',
 'fi210909a.1111',
 'fi211125a.1210',
 'fi210819a.0272',
 'fi210908a.0416',
 'fi211020a.0707',
 'fi211115a.1131',
 'fi211118a.2230',
 'fi211014a.0866',
 'fi211123a.1849',
 'fi210927a.0256',
 'fi211012a.0198',
 'fi211014a.0496',
 'fi211012a.1368',
 'fi210831a.0611',
 'fi210721a.0852',
 'fi210801a.0518',
 'fi210812a.1697',
 'fi211012a.1952',
 'fi210822a.0805',
 'fi211118a.1515',
 'fi211012a.1230',
 'fi211021a.0817',
 'fi211115a.1851',
 'fi210901a.0354',
 'fi211018a.1037',
 'fi210822a.0160',
 'fi211124a.1401',
 'fi210714a.1269',
 'fi210824a.0256',
 'fi210811a.1940',
 'fi211021a.0017',
 'fi210712a.0496',
 'fi211017a.0997',
 'fi210714a.0321',
 'fi210720a.0034',
 'fi210720a.1024',
 'fi211110a.2309',
 'fi210909a.1714',
 'fi210824a.0481',
 'fi210823a.0533',
 'fi210815a.0367',
 'fi210815a.0954',
 'fi211108a.0282',
 'fi210823a.0371',
 'fi210812a.0813',
 'fi211018a.1833',
 'fi211017a.2309',
 'fi210823a.0987',
 'fi210824a.1564',
 'fi211118a.1852',
 'fi210714a.0311',
 'fi210725a.0269',
 'fi210908a.0811',
 'fi211108a.1339',
 'fi211020a.0389',
 'fi211115a.0751',
 'fi210810a.0769',
 'fi211017a.1199',
 'fi211103a.0545',
 'fi211104a.1279',
 'fi210720a.0803',
 'fi211125a.0197',
 'fi211020a.0561',
 'fi210824a.1633',
 'fi211102a.0976',
 'fi211125a.0899',
 'fi210831a.1022',
 'fi211026a.1464',
 'fi211117a.1426',
 'fi211018a.1886',
 'fi211019a.1370',
 'fi211115a.0368',
 'fi211104a.1590',
 'fi211102a.0801',
 'fi211117a.0210',
 'fi210809a.0507',
 'fi210705a.0053',
 'fi210809a.0171',
 'fi211104a.1615',
 'fi210818a.0483',
 'fi210721a.0858',
 'fi211123a.1836',
 'fi210823a.0833',
 'fi211124a.1408',
 'fi210729a.0947',
 'fi210817a.0769',
 'fi210817a.0469',
 'fi211020a.0466',
 'fi211019a.1501',
 'fi211115a.1177',
 'fi211117a.1105',
 'fi211123a.1449',
 'fi211102a.1052',
 'fi210831a.0045',
 'fi210715a.0262',
 'fi210907a.0132',
 'fi210819a.0105',
 'fi211102a.0588',
 'fi211108a.1301',
 'fi210722a.1157',
 'fi211108a.1040',
 'fi211108a.2502',
 'fi211108a.1335',
 'fi211124a.1158',
 'fi211025a.1394',
 'fi211115a.1760',
 'fi210719a.1340',
 'fi211110a.0633',
 'fi210719a.1213',
 'fi210812a.0538',
 'fi210815a.0177',
 'fi211017a.0178',
 'fi211125a.1261',
 'fi210721a.0939',
 'fi210729a.0863',
 'fi211109a.0868',
 'fi211118a.1229',
 'fi211124a.1665',
 'fi210721a.0462',
 'fi210810a.0408',
 'fi210809a.0045',
 'fi211103a.1266',
 'fi211108a.0010',
 'fi211025a.1280',
 'fi210831a.0008',
 'fi211110a.1513',
 'fi210701a.0026',
 'fi210707a.0085',
 'fi211104a.0890',
 'fi211111a.0629',
 'fi211117a.2079',
 'fi210818a.0765',
 'fi211118a.2374',
 'fi210901a.0591',
 'fi210819a.1510',
 'fi211012a.1843',
 'fi210725a.0402',
 'fi211019a.0623',
 'fi211124a.0892',
 'fi211108a.1600',
 'fi210725a.0921',
 'fi210715a.1276',
 'fi211111a.1912',
 'fi211124a.0706',
 'fi210819a.1094',
 'fi210909a.0261',
 'fi211010a.0562',
 'fi211118a.0393',
 'fi211014a.0028',
 'fi211025a.1962',
 'fi211018a.1719',
 'fi211124a.1153',
 'fi211012a.1162',
 'fi210722a.1058',
 'fi211018a.0748',
 'fi210721a.1142',
 'fi210721a.0228',
 'fi210809a.0205',
 'fi211122a.0671',
 'fi211125a.0755',
 'fi210809a.0459',
 'fi211108a.2210',
 'fi211115a.2018',
 'fi211118a.0421',
 'fi210901a.1648',
 'fi211108a.0079',
 'fi210823a.0322',
 'fi211103a.1919',
 'fi210726a.0470',
 'fi211018a.0313',
 'fi211115a.0564',
 'fi211102a.1697',
 'fi210818a.0875',
 'fi211123a.2053',
 'fi210728a.0550',
 'fi211019a.2095',
 'fi211109a.1826',
 'fi210824a.0888',
 'fi211012a.0029',
 'fi210809a.0972',
 'fi210719a.0815',
 'fi211118a.2022',
 'fi210902a.1365',
 'fi211026a.0655',
 'fi211122a.1431',
 'fi210819a.0433',
 'fi211025a.1604',
 'fi210817a.1162',
 'fi211117a.2259',
 'fi210901a.1282',
 'fi211012a.2091',
 'fi210816a.0325',
 'fi211104a.2112',
 'fi211025a.1395',
 'fi210720a.0348',
 'fi210729a.1175',
 'fi210816a.0801',
 'fi211104a.2335',
 'fi210817a.0456',
 'fi210728a.0247',
 'fi210811a.0627',
 'fi210812a.1039',
 'fi211014a.1306',
 'fi211026a.0853',
 'fi210822a.1104',
 'fi211104a.1053',
 'fi210721a.0271',
 'fi211124a.0791',
 'fi210816a.0665',
 'fi210728a.0170',
 'fi210719a.0473',
 'fi210721a.0157',
 'fi211111a.1420',
 'fi210812a.1187',
 'fi210819a.1217',
 'fi210818a.0028',
 'fi210727a.0893',
 'fi211115a.1573',
 'fi210810a.1261',
 'fi210831a.0150',
 'fi211014a.0432',
 'fi210830a.0500',
 'fi211122a.1361',
 'fi211110a.1308',
 'fi210927a.0229',
 'fi211123a.0176',
 'fi210809a.0761',
 'fi210726a.0933',
 'fi211124a.1430',
 'fi211122a.0494',
 'fi211108a.1901',
 'fi210722a.0703',
 'fi211020a.0771',
 'fi211118a.2406',
 'fi211010a.0656',
 'fi210901a.0199',
 'fi210901a.0207',
 'fi211021a.1357',
 'fi211110a.2261',
 'fi211117a.0767',
 'fi210811a.0743',
 'fi210901a.0231',
 'fi211103a.1813',
 'fi211117a.2307',
 'fi210810a.0453',
 'fi210816a.0929',
 'fi210714a.0808',
 'fi211017a.0520',
 'fi211102a.1641',
 'fi210729a.0826',
 'fi211018a.1857',
 'fi211017a.2402',
 'fi210822a.0477',
 'fi210901a.1234',
 'fi211019a.1286',
 'fi210819a.1226',
 'fi210822a.0381',
 'fi210725a.0950',
 'fi210907a.0079',
 'fi211124a.0775',
 'fi210811a.0595',
 'fi211102a.1308',
 'fi210830a.0158',
 'fi210720a.1084',
 'fi211123a.0690',
 'fi210704a.0087',
 'fi211019a.1980',
 'fi211124a.0363',
 'fi211109a.0016',
 'fi210824a.0760',
 'fi211025a.1890',
 'fi211026a.1408',
 'fi211017a.1124',
 'fi210824a.0133',
 'fi211118a.0198',
 'fi210819a.0911',
 'fi210728a.0138',
 'fi211017a.0975',
 'fi211118a.1070',
 'fi211104a.0034',
 'fi210718a.0091',
 'fi210719a.0687',
 'fi211115a.0274',
 'fi211102a.1143',
 'fi210728a.0886',
 'fi210824a.1131',
 'fi211102a.1203',
 'fi211012a.2082',
 'fi211103a.1823',
 'fi210801a.0621',
 'fi210902a.0096',
 'fi210811a.1107',
 'fi210830a.0461',
 'fi211014a.0969',
 'fi211115a.1235',
 'fi210822a.1065',
 'fi210721a.1056',
 'fi211110a.2116',
 'fi211111a.1670',
 'fi211018a.0764',
 'fi211122a.0762',
 'fi210718a.0174',
 'fi211118a.1078',
 'fi211125a.0012',
 'fi211123a.2024',
 'fi210815a.0065',
 'fi211019a.0387',
 'fi210812a.0176',
 'fi210902a.0682',
 'fi210909a.0620',
 'fi211019a.1952',
 'fi211110a.0180',
 'fi211017a.0309',
 'fi210907a.0378',
 'fi210722a.1210',
 'fi210720a.0327',
 'fi211018a.0412',
 'fi211102a.1214',
 'fi210728a.0389',
 'fi210819a.0407',
 'fi211017a.0611',
 'fi211123a.2120',
 'fi211117a.0738',
 'fi210901a.0195',
 'fi210728a.0518',
 'fi210722a.0168',
 'fi211122a.1118',
 'fi211019a.0908',
 'fi210714a.1187',
 'fi210810a.0708',
 'fi210810a.1121',
 'fi211109a.1136',
 'fi210901a.1415',
 'fi210712a.0702',
 'fi210809a.0628',
 'fi210707a.0303',
 'fi211103a.1229',
 'fi210707a.0245',
 'fi211111a.1655',
 'fi211104a.1370',
 'fi211124a.1250',
 'fi210817a.0353',
 'fi211017a.1232',
 'fi210817a.0797',
 'fi211017a.1553',
 'fi211019a.0865',
 'fi211014a.0631',
 'fi210728a.0571',
 'fi210721a.0953',
 'fi210727a.0682',
 'fi211108a.1892',
 'fi210728a.0864',
 'fi210901a.0472',
 'fi211108a.2040',
 'fi211017a.0034',
 'fi210810a.0837',
 'fi211122a.1728',
 'fi210817a.1003',
 'fi211014a.0568',
 'fi210810a.1054',
 'fi211025a.1274',
 'fi210719a.0257',
 'fi211117a.1504',
 'fi211103a.0190',
 'fi210812a.0660',
 'fi211110a.0415',
 'fi211122a.0191',
 'fi210815a.0772',
 'fi210822a.1042',
 'fi210902a.1421',
 'fi210712a.0598',
 'fi211104a.1008',
 'fi211018a.0972',
 'fi210721a.0805',
 'fi211012a.2016',
 'fi210712a.0511',
 'fi211014a.0723',
 'fi210714a.0331',
 'fi211103a.1474',
 'fi210711a.0067',
 'fi211124a.0036',
 'fi210901a.0859',
 'fi211021a.0737',
 'fi211103a.0395',
 'fi211122a.0156',
 'fi210726a.0145',
 'fi210728a.0869',
 'fi210812a.1475',
 'fi210831a.0919',
 'fi211108a.1397',
 'fi211025a.1445',
 'fi211019a.1937',
 'fi210801a.0174',
 'fi211025a.0612',
 'fi210901a.0793',
 'fi210801a.0424',
 'fi211026a.0037',
 'fi211025a.1728',
 'fi210715a.0158',
 'fi210908a.0956',
 'fi210909a.1133',
 'fi211017a.2124',
 'fi211117a.1188',
 'fi211111a.1914',
 'fi210812a.0397',
 'fi210726a.0054',
 'fi210726a.0249',
 'fi211018a.1186',
 'fi210824a.0231',
 'fi210720a.0206',
 'fi211117a.1770',
 'fi210811a.0166',
 'fi210719a.0122',
 'fi210819a.0574',
 'fi211010a.0184',
 'fi210927a.0175',
 'fi211110a.1708',
 'fi210812a.0145',
 'fi210824a.1578',
 'fi211125a.1328',
 'fi210714a.1202',
 'fi210719a.0093',
 'fi211102a.1507',
 'fi210728a.0176',
 'fi210824a.0367',
 'fi211012a.2079',
 'fi211014a.0043',
 'fi211014a.0451',
 'fi210714a.1176',
 'fi210824a.0669',
 'fi211111a.0791',
 'fi211019a.1062',
 'fi211110a.0044',
 'fi210811a.1629',
 'fi210815a.0773',
 'fi210816a.1048',
 'fi211017a.2393',
 'fi211104a.2372',
 'fi210801a.0126',
 'fi210720a.0049',
 'fi211109a.1896',
 'fi211021a.1283',
 'fi211123a.0752',
 'fi211019a.1831',
 'fi211115a.1556',
 'fi210721a.0550',
 'fi210810a.1033',
 'fi210728a.0309',
 'fi210714a.0477',
 'fi210819a.0416',
 'fi210909a.1449',
 'fi211017a.0895',
 'fi210715a.0914',
 'fi211025a.1342',
 'fi211018a.0976',
 'fi210816a.0392',
 'fi210728a.1204',
 'fi211115a.0796',
 'fi210812a.1075',
 'fi211103a.0267',
 'fi211110a.1385',
 'fi210907a.0277',
 'fi211012a.0008',
 'fi211026a.0454',
 'fi210831a.0659',
 'fi210824a.0268',
 'fi210712a.1116',
 'fi210720a.0748',
 'fi210823a.0068',
 'fi211104a.0674',
 'fi211021a.1352',
 'fi210712a.0246',
 'fi210812a.0503',
 'fi211103a.0567',
 'fi211108a.1152',
 'fi210818a.0814',
 'fi210812a.0299',
 'fi211018a.1359',
 'fi210823a.0173',
 'fi210810a.0774',
 'fi210909a.0515',
 'fi210818a.0832',
 'fi211102a.0607',
 'fi210902a.1323',
 'fi210909a.0318',
 'fi211017a.2131',
 'fi211111a.0913',
 'fi210809a.1117',
 'fi211021a.0210',
 'fi210812a.0297',
 'fi210818a.0928',
 'fi210718a.0255',
 'fi211102a.1321',
 'fi211102a.1867',
 'fi211104a.2274',
 'fi211124a.0960',
 'fi210714a.0891',
 'fi210815a.0393',
 'fi210823a.0551',
 'fi211018a.0468',
 'fi211025a.0903',
 'fi210728a.1008',
 'fi210812a.1218',
 'fi210720a.0644',
 'fi210811a.1380',
 'fi211117a.0220',
 'fi210729a.0512',
 'fi210809a.0182',
 'fi210810a.1222',
 'fi210801a.0056',
 'fi211108a.0742',
 'fi211108a.0647',
 'fi211108a.2254',
 'fi211017a.0617',
 'fi211108a.0439',
 'fi210721a.0918',
 'fi210722a.1028',
 'fi210714a.0762',
 'fi210810a.0075',
 'fi210812a.1115',
 'fi211103a.1705',
 'fi211117a.0259',
 'fi211118a.0653',
 'fi211017a.1991',
 'fi211109a.0697',
 'fi211123a.0704',
 'fi211012a.1784',
 'fi211109a.1638',
 'fi211018a.1691',
 'fi211117a.0552',
 'fi211110a.1411',
 'fi211124a.0876',
 'fi211020a.0192',
 'fi211110a.1608',
 'fi211108a.0797',
 'fi210715a.0948',
 'fi210927a.0141',
 'fi210726a.0467',
 'fi211125a.0788',
 'fi210721a.0109',
 'fi210824a.1705',
 'fi210816a.1377',
 'fi211019a.1802',
 'fi211109a.1514',
 'fi210901a.1352',
 'fi211018a.0897',
 'fi211108a.0611',
 'fi210722a.0080',
 'fi211014a.1282',
 'fi211108a.1326',
 'fi210713a.0397',
 'fi210907a.0243',
 'fi211102a.0615',
 'fi210704a.0102',
 'fi210816a.0210',
 'fi211025a.0772',
 'fi211111a.1377',
 'fi210720a.0943',
 'fi211110a.0652',
 ...}

In [218]:
len(set(df['filename'].to_list()).intersection(trials_set))

82558

In [219]:
base_path

PosixPath('/home/barak/Projects/population-analysis/data/csst_trials_pkls')

In [220]:
fi_maestro_base_path = base_path.parent / 'from_indra' / 'fiona_sst'

# Get set of all filenames in subfolders
all_files_on_disk = set(p.name for p in fi_maestro_base_path.rglob('*') if p.is_file())

# Check existence
found_trials = [t for t in trials_set if t in all_files_on_disk]
missing_trials = [t for t in trials_set if t not in all_files_on_disk]

print(f"Total trials in set: {len(trials_set)}")
print(f"Found on disk: {len(found_trials)}")
print(f"Missing: {len(missing_trials)}")

if missing_trials:
    print(f"Example missing: {missing_trials[:5]}")

Total trials in set: 93663
Found on disk: 93643
Missing: 20
Example missing: ['fi211125a.1780', 'fi211125a.1768', 'fi211125a.1769', 'fi211125a.1771', 'fi211125a.1772']

In [221]:
print([t for t in missing_trials if 'a' in t])

['fi211125a.1780', 'fi211125a.1768', 'fi211125a.1769', 'fi211125a.1771', 'fi211125a.1772', 'fi211125a.1773', 'fi211125a.1776', 'fi211125a.1777', 'fi211125a.1762', 'fi211125a.1775', 'fi211125a.1761', 'fi211125a.1765', 'fi211125a.1763', 'fi211125a.1766', 'fi211125a.1767', 'fi211125a.1770', 'fi211125a.1764', 'fi211125a.1779', 'fi211125a.1778', 'fi211125a.1774']

In [222]:
msn_cells.apply(
    lambda row: (f"{row['session']}{row['plexon_session']}", row['cell_type']), 
    axis=1 #, result_type='expand'
).nunique()

162

In [223]:
# Get unique sessions from the DataFrame
unique_msn_sessions = msn_cells['session'].unique()

# Check existence of session folders
missing_session_dirs = []
for session in unique_msn_sessions:
    session_dir = fi_maestro_base_path / session
    if not session_dir.exists() or not session_dir.is_dir():
        missing_session_dirs.append(session)

print(f"Total unique MSN sessions: {len(unique_msn_sessions)}")
print(f"Missing session directories: {len(missing_session_dirs)}")

if missing_session_dirs:
    print(f"Missing directories: {missing_session_dirs}")
else:
    print("All session directories exist.")

Total unique MSN sessions: 66
Missing session directories: 0
All session directories exist.

In [224]:
msn_cells

,cell_ID,session,cell_type,electrode,template,maestro_ID,phy_id,phy_channel,file_begin,file_end,...,X,Y,depth_mm,is_continuous,comments,plex_sorted_file,tmp,sorted,problem,synced_stability
0,9002,fi210629,msn,1,1,1,NaN,NaN,84,163,...,0,-1,10200.0,2,NaN,fi210629a-01.pl2,NaN,1,NaN,1
1,9003,fi210701,msn,1,1,1,NaN,NaN,16,348,...,0,-1,7030.0,2,2 cells multi unit,fi210701a-02.pl2,NaN,1,NaN,1
2,9005,fi210701,msn,1,2,2,NaN,NaN,16,348,...,0,-1,7030.0,2,NaN,fi210701a-02.pl2,NaN,1,NaN,1
3,9006,fi210704,msn,1,1,1,NaN,NaN,15,191,...,0,-3,5120.0,2,NaN,fi210704a-02.pl2,NaN,1,NaN,1
4,9007,fi210705,msn,1,1,1,NaN,NaN,35,317,...,0,-5,4670.0,2,NaN,fi210705a-01.pl2,NaN,1,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4201,4376,fi211125,pu msn,97,1,28,NaN,NaN,1077,1780,...,-8,-1,NaN,2,NaN,fi211125b-06.pl2,17650.0,1,NaN,1
4202,4377,fi211125,pu msn,102,1,29,NaN,NaN,1077,1780,...,-8,-1,NaN,2,NaN,fi211125b-06.pl2,17650.0,1,NaN,1
4203,4379,fi211125,pu msn,119,1,31,NaN,NaN,1077,1780,...,-8,-1,NaN,2,NaN,fi211125b-06.pl2,17650.0,1,NaN,1
4204,4380,fi211125,pu msn,120,1,32,NaN,NaN,1077,1780,...,-8,-1,NaN,2,NaN,fi211125b-06.pl2,17650.0,1,NaN,1
4205,4381,fi211125,pu msn,127,1,33,NaN,NaN,1077,1780,...,-8,-1,NaN,2,NaN,fi211125b-06.pl2,17650.0,1,NaN,1

In [225]:
cell_db['session'].unique().shape
cell_db[cell_db['cell_type'] == 'msn']

,cell_ID,session,cell_type,electrode,template,maestro_ID,phy_id,phy_channel,file_begin,file_end,...,X,Y,depth_mm,is_continuous,comments,plex_sorted_file,tmp,sorted,problem,synced_stability
1,9002,fi210629,msn,1,1,1,NaN,NaN,84,163,...,0,-1,10200.0,2,NaN,fi210629a-01.pl2,NaN,1,NaN,1
2,9003,fi210701,msn,1,1,1,NaN,NaN,16,348,...,0,-1,7030.0,2,2 cells multi unit,fi210701a-02.pl2,NaN,1,NaN,1
4,9005,fi210701,msn,1,2,2,NaN,NaN,16,348,...,0,-1,7030.0,2,NaN,fi210701a-02.pl2,NaN,1,NaN,1
5,9006,fi210704,msn,1,1,1,NaN,NaN,15,191,...,0,-3,5120.0,2,NaN,fi210704a-02.pl2,NaN,1,NaN,1
6,9007,fi210705,msn,1,1,1,NaN,NaN,35,317,...,0,-5,4670.0,2,NaN,fi210705a-01.pl2,NaN,1,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4951,4024,fi211118,msn,19,1,33,NaN,NaN,1063,2433,...,0,-4,NaN,2,NaN,fi211118b-06.pl2,12800.0,1,NaN,1
4952,4025,fi211118,msn,20,1,34,NaN,NaN,1063,2433,...,0,-4,NaN,2,NaN,fi211118b-06.pl2,12800.0,1,NaN,1
4953,4026,fi211118,msn,21,1,35,NaN,NaN,1063,2433,...,0,-4,NaN,2,NaN,fi211118b-06.pl2,12800.0,1,NaN,1
4954,4027,fi211118,msn,21,2,36,NaN,NaN,1063,2433,...,0,-4,NaN,2,NaN,fi211118b-06.pl2,12800.0,1,NaN,1
4955,4028,fi211118,msn,22,1,37,NaN,NaN,1063,2433,...,0,-4,NaN,2,NaN,fi211118b-06.pl2,12800.0,1,NaN,1